name: TheLowSheetPlugin
main: lbn.spread.sheet.SheetPlugin
version: 0.1
commands:
   sheet:
     description: Get all Sheets.
     usage: sorry, but i don't know this command.
     permission: ThaLowSheet.sheet
     permission-message: You don't have <permission>